version: '3'

services:
  backend:
    build: ./
    container_name: nestjs_api
    environment:
      - PORT=3000
      - JWT_SECRET=123
      - MONGO_URI=mongodb://mondo_db:27017/mongo-graphql
    ports:
      - '3000:3000'
    depends_on:
      - database
    networks:
      - nestjs_network

  database:
    image: mongo
    container_name: mongo_db
    ports:
      - '27017:27017'
    volumes:
      - './mongodb-backup:data/db'
    networks:
      - nestjs_network

networks:
  nestjs_network:
    driver: bridge
